# Generated by Django 5.0.7 on 2024-11-11 15:13

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_products_background_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='background_color',
        ),
        migrations.AddField(
            model_name='shop_info',
            name='background_color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None),
        ),
    ]
