# Generated by Django 5.0.7 on 2025-01-27 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_products_background_color_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_info',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shop_info',
            name='img',
            field=models.ImageField(default='magnit.png', upload_to='', verbose_name='Лого'),
        ),
        migrations.AlterField(
            model_name='shop_info',
            name='name',
            field=models.CharField(default='Name', max_length=255, verbose_name='Название магазина'),
        ),
        migrations.AlterField(
            model_name='shop_info',
            name='url',
            field=models.CharField(default='URL', max_length=255, verbose_name='Ссылка'),
        ),
    ]
