# Generated by Django 5.0.7 on 2025-01-27 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_shop_info_owner_alter_shop_info_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop_info',
            name='owner',
        ),
    ]
